apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jvb
  namespace: jitsi
  # needed for metacontroller to create/delete service per pod
  # https://github.com/metacontroller/metacontroller/tree/master/examples/service-per-pod
  annotations:
    service-per-pod-label: "statefulset.kubernetes.io/pod-name"
    # "port:targetport:nodeport:protocol", "octo-port:octo-targetport:octo-nodeport"
    service-per-pod-ports: "31000:31000:31000:UDP,30960:30960:30960:UDP,30900:30900:30900:TCP"
spec:
  serviceName: "jvb" #Do not use '-' in name.
  replicas: 1
  selector:
    matchLabels:
      app: jvb
  template:
    metadata:
      labels:
        app: jvb
    spec:
      containers:  
        - name: jvb
          image: jitsi/jvb:stable-5390-3
          imagePullPolicy: Always
          # resources:
          #   limits:
          #     cpu: "4000m"
          #   requests:
          #     cpu: "3000m"
          volumeMounts:
          - name: jvb-config
            mountPath: /etc/cont-init.d/10-config
            subPath: 10-config
          - name: jvb-config
            mountPath: /etc/jitsi/videobridge/config
            subPath: config
          - name: jvb-config
            mountPath: /defaults/sip-communicator.properties
            subPath: sip-communicator.properties
          - name: jvb-config
            mountPath: /defaults/jvb.conf
            subPath: jvb.conf
          env:
            - name: ENABLE_JVB_WEBSOCKET
              value: "1"
            - name: TESTING_OCTO_PROBABILITY
              value: "1"
            - name: XMPP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: jitsi-config
                  key: XMPP_SERVER
            - name: DOCKER_HOST_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: jitsi-config
                  key: DOCKER_HOST_ADDRESS
            - name: PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: jitsi-config
                  key: PUBLIC_URL
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: JVB_STUN_SERVERS
              value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: JVB_TCP_PORT
              value: "4443"
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_ENABLE_APIS
              value: rest,colibri
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
            - name: OCTO_REGION
              valueFrom:
                configMapKeyRef:
                  name: web-shard-config
                  key: OCTO_REGION
            - name: JVB_CC_ENABLE
              value: "false"
            - name: JVB_BWE_CHANGE_THRESHOLD
              value: "0.15"
            - name: JVB_THUMBNAIL_MAX_HEIGHT
              value: "180"
            - name: JVB_ONSTAGE_IDEAL_HEIGHT
              value: "1080"
            - name: JVB_ONSTAGE_PREF_HEIGHT
              value: "360"
            - name: JVB_ONSTAGE_PREF_FRAMERATE
              value: "30"
            - name: JVB_ALLOW_OVERSEND_ONSTAGE
              value: "true"
            - name: JVB_TRUST_BWE
              value: "true"
            - name: JVB_CC_PADDING_PERIOD
              value: "15ms"
            - name: JVB_FORWARD_STEAM_RECALCULATION
              value: "15 seconds"
            - name: JVB_LAST_N
              value: "15"
            - name: JVB_COLIBRI_API_ENABLE
              value: "true"
            - name: JVB_API_ENABLE
              value: "true"
            - name: JVB_REST_API_ENABLE
              value: "true"
            - name: JVB_REST_DEBUG_ENABLE
              value: "true"
            - name: JVB_REST_HEALTH_ENABLE
              value: "true"
            - name: JVB_REST_SHUTDOWN_ENABLE
              value: "true"
            - name: JVB_LOAD_MGMT_ENABLE
              value: "false"
            - name: JVB_LOAD_MGMT_REDUCER_ENABLE
              value: "false"
            - name: JVB_PKT_RATE_LOAD_THRESHOLD
              value: "50000"
            - name: JVB_PKT_RATE_RCVRY_THRESHOLD
              value: "40000"
            - name: JVB_LOAD_REDUCER_ENABLE
              value: "false"
            - name: JVB_LAST_N_REDUCTION_SCALE
              value: "0.75"
            - name: JVB_LAST_N_RECOVER_SCALE
              value: "1.25"
            - name: JVB_LAST_N_IMPACT_TIME
              value: "1 min"
            - name: "JVB_MIN_LAST_N_VAL"
              value: "1"
            - name: JVB_MAX_ENFORCED_LAST_N_VAL
              value: "40"      
      volumes:
      - name: jvb-config
        configMap:
          name: jvb-base
          defaultMode: 0777
          items:
          - key: config
            path: config
          - key: 10-config
            path: 10-config
          - key: sip-communicator.properties
            path: sip-communicator.properties
          - key: jvb.conf
            path: jvb.conf